### ISSUE TITLE
hasHeader: false skipping first row

### ISSUE THREAD

**Issue by jakub-gawryl** [bigabdoul/fast-xlsx-reader#1]
When i set ` hasHeader: false` in options, first row is skipped in "onRecord" callback.

Example excel file:
![obraz](https://user-images.githubusercontent.com/6490966/80810080-563ddd80-8bc3-11ea-81af-63605dec6237.png)

Example result:
![obraz](https://user-images.githubusercontent.com/6490966/80810115-6e156180-8bc3-11ea-9bd8-2529ffcdbf87.png)

I'm using schema:
`const schema = [
  {prop: "A"},
  {prop: "B"},
  {prop: "C"},
  {prop: "D"}
];`

**Comment by bigabdoul** [comment]
Alright, I will look at this. Thanks for reporting back issues.
