### ISSUE TITLE
Request to add certain features.

### ISSUE THREAD

**Issue by gaurav-cointab** [bigabdoul/fast-xlsx-reader#3]
Hi I have liked this libary after going over a lot of other libraries. I have to read a very vary large excel files, and that too in batches, and in array format.

Can you introduce these features:
1. if the "format" is array, then don't try to cast each row in json.
2. if the hasHeader is false, then don't try to parse 1st row as header.
3. can we have a control over the events, like can we have a function like onRecordCallback, with 1 more parameter as callback function like a next. So the basic idea is that we can proceed further only if we have processed the current record.

**Comment by bigabdoul** [comment]
Glad that you liked this repo @gaurav-cointab! I just saw your feature request and will try to spend some time on the project. However, I have a few questions for you to further clarify your intend:

1. Can you show what the exact format of the array should be?
2. Do you mean by "control over the events" a way to cancel subsequent read operations if the 'onRecord' callback returns true (for cancel === true)? Or
3. Do you want to be able to sequentially read each row (on demand) by calling a 'readNext' function?

Thanks for given feedback.

**Comment by Zireael** [comment]
> * Can you show what the exact format of the array should be?
> * Do you mean by "control over the events" a way to cancel subsequent read operations if the 'onRecord' callback returns true (for cancel === true)? Or
> * Do you want to be able to sequentially read each row (on demand) by calling a 'readNext' function?

Not the original question author, but I would see the answers like so:
1) ` [[1,2,3],[9,4,7],["ABC",5,"cat"],[9,0,4],[3,2,1]]`     (array of arrays/rows)
2) He probably wanted to process each row as it gets read and get reader() to wait until that row/chunk is processed. A good illustration would be NodeJS [stream.pipe approach](https://nodesource.com/blog/understanding-streams-in-nodejs/):

```JavaScript
const Stream = require('stream')

// I'll try to translate a NodeJS example to Excel reading example:

const readableStream = new Stream.Readable() // xlsx reader
const writableStream = new Stream.Writable() // something that processes each row

writableStream._write = (chunk, encoding, next) => { // receive a row
    console.log(chunk.toString()) // process row
    next() // request next row
}

readableStream.pipe(writableStream) // redirect row stream (in chunks, one row after another row) from xlsx reader to row processor

readableStream.push('ping!') // read some excel file
readableStream.push('pong!') // read another excel file

writableStream.end()
```
 
3) By calling in callback either something like `reader.readNext()` to get the next row or  `reader.reset()` to cancel reading

**Comment by bigabdoul** [comment]
The lately introduced FastXlsxSheetReader class handles the requested features in an object-oriented way. It provides a few methods that allow you to manipulate your workbooks in a very flexible manner. See the documentation in README.md.
