### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by lmazlouly** [bigabdoul/fast-xlsx-reader#4]
Could you guys please on the next version change this method at line **428** ->**\lib\FastXlsxReader.js**
To avoid `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined`  
 **OLD**
```javascript
static _normalizeHeader(row, lowerCase) {
    row.forEach((column, index) => {
      let col = column.toString().trim();
      if (lowerCase) col = col.toLowerCase();
      row[index] = col;
    });
    return row;
  }
```
**NEW**
```javascript
static _normalizeHeader(row, lowerCase) {
    row.forEach((column, index) => {
      try {
        if(column){
          let col = column.toString().trim();
          if (lowerCase) col = col.toLowerCase();
          row[index] = col;
        } else {
          row[index] = '';
        }
      } catch (error) { }
    });
    return row;
  }
```

EDIT: sorry for posting it here since i have no idea about how to use Github properly all i know is git pull n push ahhahaha

**Comment by bigabdoul** [comment]
@Imazlouly currently away from my dev computer. Will fix it asap...

**Comment by Zireael** [comment]
I was getting the same error. Can confirm the proposed code swap fixed the issue for me.
